# Generated by Django 4.1.5 on 2023-02-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_event_contract"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="contract",),
    ]
