# Generated by Django 4.1.5 on 2023-02-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_remove_event_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="contract",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event",
                to="crm.contract",
            ),
            preserve_default=False,
        ),
    ]
